export const SELECT_GIST = 'SELECT_GIST';

/**
 * Action typet
 */

//Gistien hakeminen
export const FETCH_GISTS_REQUEST = 'FETCH_GISTS_REQUEST';
export const FETCH_GISTS_SUCCESS = 'FETCH_GISTS_SUCCESS';
export const FETCH_GISTS_FAILURE = 'FETCH_GISTS_FAILURE';

//Aktiivisen gistin asettaminen
export const FETCH_ACTIVE_GIST_REQUEST = 'FETCH_ACTIVE_GIST_REQUEST';
export const FETCH_ACTIVE_GIST_SUCCESS = 'FETCH_ACTIVE_GIST_SUCCESS';
export const FETCH_ACTIVE_GIST_FAILURE = 'FETCH_ACTIVE_GIST_FAILURE';